### PR TITLE
Fix scope not being reset when navigating to fresh entry form

### PR DESCRIPTION
**Pull request by Anahkiasen**
### Fixed

- Fix scope not being reset when navigating to fresh entry form

---

Ticket: https://jira.uitdatabank.be/browse/III-5427

### CODE REVIEW

**Comment by simon-debruijn** [comment]
@Anahkiasen Can you make sure you didn't break what this PR fixed:

https://github.com/cultuurnet/udb3-frontend/pull/647

https://jira.uitdatabank.be/browse/III-5395

**Comment by Anahkiasen** [comment]
Nope indeed it brings it back, will find another way

**Comment by Anahkiasen** [comment]
@simon-debruijn Ok actually after banging my head on this a bunch it seems the bug still happens on `main` even without any changes. Could something else have brought back the `calendarType: single` bug?

**Comment by simon-debruijn** [comment]
Could you verify this is still an issue after changes from https://github.com/cultuurnet/udb3-frontend/pull/664

**Comment by Anahkiasen** [comment]
@simon-debruijn Works now with the fix + latest changes on main 👍

**Review by simon-debruijn — APPROVED** [review]

**Review by brampauwelyn — APPROVED** [review]

**Pull request merged**
