### PR TITLE
III-5220 - Add conversion page to try beta preview

### PR DESCRIPTION
**Pull request by simon-debruijn**
### Added

- Add conversion page to try beta preview

---

Ticket: https://jira.uitdatabank.be/browse/III-5220

Screenshot 2023-02-24 at 16 27 14

### CODE REVIEW

**Comment by simon-debruijn** [comment]
@corneelwille You can leave the correct copy here in the PR, or in the comments of the ticket 😄

**Comment by simon-debruijn** [comment]
The final copy for nl fr and de will be added in a later PR.

**Review by brampauwelyn — APPROVED** [review]
Smoooth, Works well. 👍 


Nit: 
The buttons don't have the same height on smaller screens, maybe use flex to stretch both buttons so they have an equal height.

Screenshot 2023-02-24 at 16 36 56

Once you selected "Ik probeer het uit".
The "beta toggle" button is still disabled in the sidebar, ideally  this should be in sync.
Screenshot 2023-02-24 at 16 44 11

**Comment by simon-debruijn** [comment]
> The "beta toggle" button is still disabled in the sidebar, ideally this should be in sync.

I've been able to fix `The "beta toggle" button is still disabled in the sidebar, ideally this should be in sync.`.

The button height seems to be caused by different implementations of firefox and chrome when using `justify-content: flex-start;` and `height: 100;` together. So I'll ignore it for now.

**Comment by simon-debruijn** [comment]
> > The "beta toggle" button is still disabled in the sidebar, ideally this should be in sync.
> 
> I've been able to fix `The "beta toggle" button is still disabled in the sidebar, ideally this should be in sync.`.
> 
> The button height seems to be caused by different implementations of firefox and chrome when using `justify-content: flex-start;` and `height: 100;` together. So I'll ignore it for now.

Also seems to work on safari, I'm blaming Firefox 😉

**Pull request merged**
