### PR TITLE
III-5280 - Add maxWidth on streetAndNumber field

### PR DESCRIPTION
**Pull request by brampauwelyn**
### Changed
- maxWidth on streetAndNumber field

Screenshot 2023-02-10 at 14 02 02

---
Ticket: https://jira.uitdatabank.be/browse/III-5280

### CODE REVIEW

**Comment by Anahkiasen** [comment]
@corneelwille It does mean the new placeholders get cut off though

Screenshot 2023-02-10 at 14 20 19

**Comment by Anahkiasen** [comment]
@corneelwille This means the new placeholders get cut off no?

Screenshot 2023-02-10 at 14 21 37

**Review by simon-debruijn — APPROVED** [review]

**Comment by corneelwille** [comment]
> @corneelwille This does means the new placeholders get cut off though
> 
> Screenshot 2023-02-10 at 14 21 37

mmh yes, not ideal at all. Maybe we can put the "Nieuwe locatie toevoegen: {{entered location name}}" on a new line?

**Comment by brampauwelyn** [comment]
> > @corneelwille This does means the new placeholders get cut off though
> > Screenshot 2023-02-10 at 14 21 37
> 
> mmh yes, not ideal at all. Maybe we can put the "Nieuwe locatie toevoegen: {{entered location name}}" on a new line?

Actually this was already the case, this input field didn't change... 
But we can make it larger if necessary

**Comment by corneelwille** [comment]
Alternatives:
Screenshot 2023-02-10 at 14 36 31

Screenshot 2023-02-10 at 14 36 48

**Comment by brampauwelyn** [comment]
Implemented the 2nd option of Corneel's suggestions.
+ Added some padding on the new input option.

Screenshot 2023-02-20 at 13 40 44

**Pull request merged**
