### PR TITLE
Use textarea trick for html entities

### PR DESCRIPTION
**Pull request by geoffreydhuyvetters**
### Added

- use textarea trick for HTML entities

---

Ticket: https://jira.uitdatabank.be/browse/III-3472

### CODE REVIEW

**Review by simon-debruijn — APPROVED** [review]

**Comment by bertramakers** [comment]
Doesn't this keep the HTML tags inside the content?

The answer you linked in the ticket mentions this: https://stackoverflow.com/questions/7394748/whats-the-right-way-to-decode-a-string-that-has-special-html-entities-in-it/7394787#7394787

> The advantage of using this code is that tags are also preserved.

The JSFiddle also seems to show this.

The goal was to strip the HTML tags out of the content since it's not really readable right now.

**Review by bertramakers — CHANGES_REQUESTED** [review]
Marking as "requesting changes" because I don't think this achieves the requested goal.

**Comment by geoffreydhuyvetters** [comment]
@bertramakers I don't see any HTML in the actual examples, only HTML entities. Which I'm replacing with this technique.

**Review by bertramakers — APPROVED** [review]
I've added a comment to clarify the `textarea` trick. Looks good to me otherwise! 👍

**Pull request merged**
