### PR TITLE
Remove first outro

### PR DESCRIPTION
**Pull request by corneelwille**
### Changed
* Removed outro 1
* Made the "old" outro 2 outro 1 now

---

Ticket: https://jira.uitdatabank.be/browse/III-5413

### CODE REVIEW

**Comment by corneelwille** [comment]
There is now no outro 2 anymore, I assume this won't break any code?

**Comment by simon-debruijn** [comment]
> There is now no outro 2 anymore, I assume this won't break any code?

This will leave an empty p tag and too much spacing now. We also have to remove the `Paragraph` component that showed outro 2.

**Review by simon-debruijn — CHANGES_REQUESTED** [review]
This will leave an empty p tag and too much spacing now. We also have to remove the Paragraph component that showed outro 2.

**Comment by corneelwille** [comment]
Alternative solution that doesn't require any copy changes: set the max-width on `.hDJskr` to 90% (or so) again. Sorry about that!

**Comment by simon-debruijn** [comment]
Screenshot 2023-03-07 at 09 22 45

**Review by simon-debruijn — APPROVED** [review]

**Pull request merged**
